In [51]:
import numpy as np
import matplotlib.pyplot as plt
import random
import queue
import time
from IPython.display import clear_output

#Functions that will be very useful for creating/updating mazes

'''
Define the grid to be working with

**inputs:
dim = dimension size of the grid
n = number of mines

**returns:
board = the grid to be worked with
'''

def environment(dim, n):
    #start with a dim by dim zero array

    board = np.zeros((dim,dim))

    while n > 0:
        i = random.randint(0, dim - 1)
        j = random.randint(0, dim - 1)

        if board[i][j] == 9:
            pass
        else:
            board[i][j] = 9
            n -= 1

    for i in range(0, dim):
        for j in range(0, dim):
            if board[i][j] == 9:
                continue

            #check all the neighbors
            mines = 0
            rightValid = False
            leftValid = False
            upValid = False
            downValid = False
            if j - 1 >= 0:
                leftValid = True
            if j + 1 < len(board):
                rightValid = True
            if i + 1 < len(board):
                downValid = True
            if i - 1 >= 0:
                upValid = True

            #check left
            if leftValid == True:
                #check left adjacent
                if board[i][j-1] == 9:
                    #mine is here
                    mines += 1
                else:
                    #no mine is here
                    pass
                #check left & up
                if upValid == True:
                    if board[i-1][j-1] == 9:
                        #mine is here
                        mines += 1
                    else:
                        #no mine is here
                        pass
                #check left & down
                if downValid == True:
                    if board[i+1][j-1] == 9:
                        #mine is here
                        mines += 1
                    else:
                        #no mine is here
                        pass

            #check right
            if rightValid == True:
                #check right adjacent
                if board[i][j+1] == 9:
                    #mine is here
                    mines += 1
                else:
                    #no mine is here
                    pass
                #check right & up
                if upValid == True:
                    if board[i-1][j+1] == 9:
                        #mine is here
                        mines += 1
                    else:
                        #no mine is here
                        pass
                #check right & down
                if downValid == True:
                    if board[i+1][j+1] == 9:
                        #mine is here
                        mines += 1
                    else:
                        #no mine is here
                        pass

            #check up adjacent
            if upValid == True:
                if board[i-1][j] == 9:
                    #mine is here
                    mines += 1
                else:
                    #no mine is here
                    pass

            #check down adjacent
            if downValid == True:
                if board[i+1][j] == 9:
                    #mine is here
                    mines += 1
                else:
                    #no mine is here
                    pass

            board[i][j] = mines

    return board

'''
A Method to Check the Neighbors of a Cell

**inputs:
possible_moves = array of coordinates for the remaining moves
coord = tuple containing the coordinates

**returns:
neighbors = the list of neighbors for the given coordinate
'''

def checkNeighbors(possible_moves, coord):
    neighbors = []
    i = coord[0]
    j = coord[1]

    if (i+1, j) in possible_moves:
        neighbors.append((i+1, j))

    if (i-1, j) in possible_moves:
        neighbors.append((i-1, j))

    if (i, j+1) in possible_moves:
        neighbors.append((i, j+1))

    if (i, j-1) in possible_moves:
        neighbors.append((i, j-1))

    if (i+1, j+1) in possible_moves:
        neighbors.append((i+1, j+1))

    if (i-1, j-1) in possible_moves:
        neighbors.append((i-1, j-1))

    if (i+1, j-1) in possible_moves:
        neighbors.append((i+1, j-1))

    if (i-1, j+1) in possible_moves:
        neighbors.append((i-1, j+1))

    return neighbors

'''
A Method to Update the Agent Board

**inputs:
coord = tuple containing the coordinates
main_board = the main board
agent_board = the agent board

**returns:
agent_board = the grid to be worked with
coord = tuple containing the coordinates
clue = number of adjacent mines
'''

def updateBoard(coord, main_board, agent_board):
    i = coord[0]
    j = coord[1]
    agent_board[i][j] = main_board[i][j]
    clue = agent_board[i][j]
    return agent_board, coord, clue

'''
A Method to Check the Number of Uncovered Mines for a Cell

**inputs:
board = the agent board
coord = tuple containing the coordinates

**returns:
mines = the number of neighboring mines
'''

def checkMines(board, coord):
    #check all the neighbors
    mines = 0
    i = coord[0]
    j = coord[1]
    rightValid = False
    leftValid = False
    upValid = False
    downValid = False
    if j - 1 >= 0:
        leftValid = True
    if j + 1 < len(board):
         rightValid = True
    if i + 1 < len(board):
         downValid = True
    if i - 1 >= 0:
        upValid = True

    #check left
    if leftValid == True:
        #check left adjacent
        if int(board[i][j-1]) == 9 or board[i][j-1] == 0.5:
            #mine is here
            mines += 1
        else:
            #no mine is here
            pass
        #check left & up
        if upValid == True:
            if int(board[i-1][j-1]) == 9 or board[i-1][j-1] == 0.5:
                #mine is here
                mines += 1
            else:
                #no mine is here
                pass
        #check left & down
        if downValid == True:
            if int(board[i+1][j-1]) == 9 or board[i+1][j-1] == 0.5:
                #mine is here
                mines += 1
            else:
                #no mine is here
                pass

    #check right
    if rightValid == True:
        #check right adjacent
        if int(board[i][j+1]) == 9 or board[i][j+1] == 0.5:
            #mine is here
            mines += 1
        else:
            #no mine is here
            pass
        #check right & up
        if upValid == True:
            if int(board[i-1][j+1]) == 9 or board[i-1][j+1] == 0.5:
                 #mine is here
                mines += 1
            else:
                #no mine is here
                pass
        #check right & down
        if downValid == True:
            if int(board[i+1][j+1]) == 9 or board[i+1][j+1] == 0.5:
                #mine is here
                mines += 1
            else:
                #no mine is here
                pass

    #check up adjacent
    if upValid == True:
        if int(board[i-1][j]) == 9 or board[i-1][j] == 0.5:
            #mine is here
            mines += 1
        else:
            #no mine is here
            pass

    #check down adjacent
    if downValid == True:
        if int(board[i+1][j]) == 9 or board[i+1][j] == 0.5:
            #mine is here
            mines += 1
        else:
            #no mine is here
            pass

    return mines

'''
Initialize blank equation to be used for inference

**inputs:
dim = the dimension size

**returns:
equation = a list of dim**2 zeros
'''

def equation(dim):
    equation = []
    while len(equation) < dim*dim:
        equation.append(0)
    return equation

In [82]:
#check unopened neighbors of given coord for given agent board
#return the number of squares that can be definitely determined
def solveForSquareHelper(q, agent_board, main_board, coord, dim, isSafe):
    #copy agent_board into sample board
    sample = np.zeros((dim,dim))
    for i in range(0, dim):
        for j in range(0, dim):
            sample[i][j] = agent_board[i][j]
    
    print("Agent's board at beginning:")
    print(sample)
    
    #a list of the expected squares that can definitely be worked out in sample board
    definiteSquares = []
    
    #mark square as either temp mine (.5) or temp safe (10)
    if(isSafe == 0):
        sample[coord[0]][coord[1]] = .5
    else:
        sample[coord[0]][coord[1]] = 10
    
    #populate a list of all the possible moves we can make
    possible_moves = []
    for i in range(0, dim):
        for j in range(0, dim):
            if(sample[i][j] == 11):
                possible_moves.append((i, j))
    
    #populate knowledge base with known squares
    KB = []
    for i in range(0, dim):
        for j in range(0, dim):
            if(sample[i][j] != .5 and sample[i][j] != 9 and sample[i][j] != 11 and sample[i][j] != 10):
                KB.append([(i,j), sample[i][j], len(checkNeighbors(possible_moves, (i,j))), sample[i][j]])  
    
    #populate a list of the neighbors of the coord
    possible_neighbors = checkNeighbors(possible_moves,coord)

    print("Agent's board:")
    print(sample)
    for item in range(0, len(KB)):
        print("KB: ", KB[item][0], " ", KB[item][1], " ", KB[item][2], " ", KB[item][3])
        
    #go through KB to find definite moves to count
    for item in KB:
        
        for item2 in range(0, len(KB)):
            #Update the temporary clue
            if KB[item2][1] + checkMines(sample, KB[item2][0]) == KB[item2][3]:
                pass
            else:
                KB[item2][1] = KB[item2][3] - checkMines(sample, KB[item2][0])
                
        for item3 in range(0, len(KB)):
            print("KB: ", KB[item3][0], " ", KB[item3][1], " ", KB[item3][2], " ", KB[item3][3])
        
        #if clue is 0 all neighbors are safe
        if item[1] == 0:
            definiteSquares += checkNeighbors(possible_moves, item[0])
            print("all neighbors safe, coords determined: ", *(checkNeighbors(possible_moves, item[0]))) 
            
        #if number of neighbors is equal to tempClue, all are mines
        elif item[1] == item[2]:
            definiteSquares += checkNeighbors(possible_moves, item[0])
            print("all neighbors mines, coords determined: ", *(checkNeighbors(possible_moves, item[0])))

    #remove duplicates in the list of definite coords identifiable and count number of remaining coords
    definiteSquares = list(dict.fromkeys(definiteSquares))
    print("Def squares final list: ", *(definiteSquares))
    numSquaresWorkedOut = len(definiteSquares)    
  
    return numSquaresWorkedOut

In [83]:
def expectedSquares(q, coord, agent_board, main_board):
    dim = len(agent_board)
    
    # mine = 0, safe = 1
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SET AS MINE ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    squaresWorkedOut_m = solveForSquareHelper(q, agent_board, main_board, coord, dim, 0)
    print("Num squares worked out M: ", squaresWorkedOut_m)
    print("MINE VAL: ", q*squaresWorkedOut_m)
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SET AS SAFE ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    squaresWorkedOut_s = solveForSquareHelper(q, agent_board, main_board, coord, dim, 1)
    print("Num squares worked out S: ", squaresWorkedOut_s)
    print("SAFE VAL: ", (1-q)*squaresWorkedOut_s)
    numSquares = q*squaresWorkedOut_m + (1-q)*squaresWorkedOut_s
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ RETURNED VALUE ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    return numSquares

In [85]:
agent_board = [[2,11,1],[11,11,11],[11,3,11]]
main_board = [[2,2,1],[9,9,2],[2,3,9]]
q = .5
coord = (0,1)

#agent_board = [[11,1,11],[11,2,11],[11,2,11]]
#main_board = [[1,1,1],[9,2,1],[1,2,9]]
#q = .33
#coord = (1,0)

#agent_board = [[11,11,11,9],[11,2,2,11],[2,11,9,1],[1,11,11,11]]
#main_board = [[1,1,1,9],[9,2,2,2],[2,3,9,1],[1,9,2,1]]
#q = .5
#coord = (0,0)

print ("The expected number of squares that could be worked out is", expectedSquares(q, coord, agent_board, main_board))

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SET AS MINE ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Agent's board from beginning:
[[  2.  11.   1.]
 [ 11.  11.  11.]
 [ 11.   3.  11.]]
Agent's board:
[[  2.    0.5   1. ]
 [ 11.   11.   11. ]
 [ 11.    3.   11. ]]
KB:  (0, 0)   2.0   2   2.0
KB:  (0, 2)   1.0   2   1.0
KB:  (2, 1)   3.0   5   3.0
KB:  (0, 0)   1.0   2   2.0
KB:  (0, 2)   0.0   2   1.0
KB:  (2, 1)   3.0   5   3.0
KB:  (0, 0)   1.0   2   2.0
KB:  (0, 2)   0.0   2   1.0
KB:  (2, 1)   3.0   5   3.0
all neighbors safe, coords determined:  (1, 2) (1, 1)
KB:  (0, 0)   1.0   2   2.0
KB:  (0, 2)   0.0   2   1.0
KB:  (2, 1)   3.0   5   3.0
Def squares final list:  (1, 2) (1, 1)
Num squares worked out M:  2
MINE VAL:  1.0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ SET AS SAFE ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Agent's board from beginning:
[[  2.  11.   1.]
 [ 11.  11.  11.]
 [ 11.   3.  11.]]
Agent's board:
[[  2.  10.   1.]
 [ 11.  11.  11.]
 [ 11.   3.  11.]]
KB:  (0, 0)   2.